model_name: xgboost_classifier
model_version: 1.0
random_state: 1
learning_rate: 0.01
threshold_in_minutes: 15
top_10_features:
  - "OPERA_Latin American Wings"
  - "MES_7"
  - "MES_10"
  - "OPERA_Grupo LATAM"
  - "MES_12"
  - "TIPOVUELO_I"
  - "MES_4"
  - "MES_11"
  - "OPERA_Sky Airline"
  - "OPERA_Copa Air"
raw_data_columns:
  - OPERA
  - TIPOVUELO
  - MES